### ISSUE TITLE
[Feature Request] macOS: have the app check for game files in Application Support

### ISSUE THREAD

**Issue by shinra-electric** [atsb/Hiigara#1]
Currently it is required to open the app bundle and place the data files in the `Resources` folder. This is a good option to have, so you can have the game self-contained.

But I think a good second option is that if the app doesn't find the data in `Resources` it then looks in `~/Library/Application Support/Hiigara`. This is a standard place to keep game data for many source ports.

**Comment by atsb** [comment]
Wow thanks for the suggestion and for using it.  I'll do that then, thanks!  Extra flexibility for users is always a good thing.

**Comment by atsb** [comment]
I took a look at this (utility.c) and it is a real mess.  What I will do is start removing all the Windows specific code, I will then remove the Linux'isms and after that, what is left will be the stuff used for macOS and there it will be easier and cleaner, to simply reimplement the entire data paths and read / write functionality.
