### ISSUE TITLE
macOS: Crash on launch - v1.1

### ISSUE THREAD

**Issue by shinra-electric** [atsb/Hiigara#4]
I placed `Homeworld.big`, `HW_Comp.vce`, `HW_Music.wxd` and `Update.big` into the `Resources` folder. Then I ran `xattr -cr` on the app bundle, and codesigned it with `codesign --force --deep --sign - `

However, it crashes on launch with the message `[1]    4914 trace trap  ./Homeworld`

**Comment by atsb** [comment]
I debugged this and it is a memory pool issue.  ARM cpu's are more strict than X86 cpu's.  What I've done is uploaded an Intel build and I have used this on an M1 machine without any issues.

I will prioritise this and will have to clean up significantly the Memory.c file for ARM machines.  My development machine is still an X86 based mac and so I am not always able to debug everything on a real M1/M2 mac.
